name: GenCI

permissions:
  contents: read

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-generalsmd:
    name: Build GeneralsMD${{ matrix.preset && '' }}
    strategy:
      matrix:
        preset: [vc6, win32]
      fail-fast: false
    uses: ./.github/workflows/reusable-build-toolchain.yml
    with:
      game: "GeneralsMD"
      preset: ${{ matrix.preset }}
      tools: true
      extras: true
      tests: ${{ matrix.preset == 'win32' }}
      benchmarks: ${{ matrix.preset == 'win32' }}
    secrets: inherit
